# Generated by Django 6.0.4 on 2026-04-29 23:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total_lots', models.IntegerField(default=0)),
                ('total_certifications', models.IntegerField(default=0)),
                ('total_agriculteurs', models.IntegerField(default=0)),
                ('total_cooperatives', models.IntegerField(default=0)),
                ('tonnage_mensuel', models.JSONField(default=dict)),
                ('repartition_certif', models.JSONField(default=dict)),
                ('zones_production', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Statistiques Dashboard',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('AGRICULTEUR', 'Agriculteur'), ('EXPORTATEUR', 'Exportateur'), ('VERIFICATEUR', 'Vérificateur'), ('TRANSFORMATEUR', 'Transformateur'), ('COOPERATIVE', 'Coopérative'), ('ADMIN', 'Admin / Ministère')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('est_verifie', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('photo_profil', models.ImageField(blank=True, upload_to='profils/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lot', models.CharField(editable=False, max_length=30, unique=True)),
                ('type_culture', models.CharField(choices=[('CACAO', 'Cacao'), ('CAFE', 'Café')], default='CACAO', max_length=10)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recolte', models.DateField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('ENREGISTRE', 'Enregistré'), ('EN_TRANSIT', 'En transit'), ('EN_TRANSFORMATION', 'En transformation'), ('TRANSFORME', 'Transformé'), ('EN_EXPORT', "En cours d'export"), ('EXPORTE', 'Exporté'), ('REFUSE', 'Refusé')], default='ENREGISTRE', max_length=20)),
                ('conforme_eudr', models.BooleanField(default=False)),
                ('prix_final_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hash_blockchain', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cert', models.CharField(choices=[('NON_DEFORESTATION', 'Non-déforestation'), ('BIO', 'Agriculture biologique'), ('FAIR_TRADE', 'Commerce équitable'), ('EUDR', 'Conformité EUDR')], max_length=30)),
                ('valide', models.BooleanField(default=False)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, upload_to='certifications/')),
                ('notes', models.TextField(blank=True)),
                ('verificateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='greenspace.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('superficie_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('region', models.CharField(max_length=100)),
                ('certifiee_non_deforestation', models.BooleanField(default=False)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='parcelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='greenspace.parcelle'),
        ),
        migrations.CreateModel(
            name='RapportEUDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, upload_to='rapports_eudr/')),
                ('hash_blockchain', models.CharField(blank=True, max_length=255)),
                ('soumis_douanes', models.BooleanField(default=False)),
                ('exportateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport_eudr', to='greenspace.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_destinataire', models.CharField(choices=[('COLLECTEUR', 'Collecteur'), ('COOPERATIVE', 'Coopérative'), ('TRANSFORMATEUR', 'Transformateur'), ('EXPORTATEUR', 'Exportateur')], max_length=20)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moyen_paiement', models.CharField(blank=True, max_length=20)),
                ('date_transfert', models.DateTimeField(auto_now_add=True)),
                ('hash_blockchain', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='greenspace.lot')),
            ],
        ),
    ]
